Repository kubescape/helm-charts, pull requests merged in 2023-09, with the labels that each got.

#280 fix relevancy config
  charts/kubescape-operator/Chart.yaml
  charts/kubescape-operator/templates/configs/cloudapi-configmap.yaml
Labels: release, Bug fix

#281 remove cloud_provider
  charts/kubescape-operator/Chart.yaml
  charts/kubescape-operator/templates/_helpers.tpl
  charts/kubescape-operator/templates/configs/cloudapi-configmap.yaml
  charts/kubescape-operator/templates/kubescape/deployment.yaml
  charts/kubescape-operator/values.yaml
Labels: Refactoring

#282 Updating readme
  .github/workflows/README.md
  README.md
  charts/kubescape-cloud-operator/README.md
  charts/kubescape-operator/README.md
Labels: Refactoring

#287 fix runAsUser for kubescape deployment
  charts/kubescape-operator/Chart.yaml
  charts/kubescape-operator/README.md
  charts/kubescape-operator/templates/kubescape/deployment.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: Bug fix

#289 Run unittests during CI
  .github/workflows/pr-created.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/tests/snapshot_test.yaml
Labels: enhancement, Tests

#292 release: bump chart version
  charts/kubescape-operator/Chart.yaml
  charts/kubescape-operator/README.md
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
Labels: enhancement
