Repository kubescape/helm-charts, pull requests merged in 2023-10, with the labels that each got.

#286 Minor changes in the README
  charts/kubescape-operator/README.md
Labels: documentation

#297 Service discovery with init containers
  charts/kubescape-operator/Chart.yaml
  charts/kubescape-operator/README.md
  charts/kubescape-operator/templates/configs/cloudapi-configmap.yaml
  charts/kubescape-operator/templates/gateway/deployment.yaml
  charts/kubescape-operator/templates/gateway/role.yaml
  charts/kubescape-operator/templates/gateway/rolebinding.yaml
  charts/kubescape-operator/templates/gateway/serviceaccount.yaml
  charts/kubescape-operator/templates/kollector/role.yaml
  charts/kubescape-operator/templates/kollector/rolebinding.yaml
  charts/kubescape-operator/templates/kollector/statefulset.yaml
  charts/kubescape-operator/templates/kubescape/deployment.yaml
  charts/kubescape-operator/templates/kubevuln/deployment.yaml
  charts/kubescape-operator/templates/kubevuln/role.yaml
  charts/kubescape-operator/templates/kubevuln/rolebinding.yaml
  charts/kubescape-operator/templates/operator/deployment.yaml
  charts/kubescape-operator/templates/otel-collector/deployment.yaml
  charts/kubescape-operator/templates/otel-collector/role.yaml
  charts/kubescape-operator/templates/otel-collector/rolebinding.yaml
  charts/kubescape-operator/templates/otel-collector/service.yaml
  charts/kubescape-operator/templates/otel-collector/serviceaccount.yaml
  charts/kubescape-operator/templates/servicediscovery/job.yaml
  charts/kubescape-operator/templates/servicediscovery/role.yaml
  charts/kubescape-operator/templates/servicediscovery/rolebinding.yaml
  charts/kubescape-operator/templates/servicediscovery/serviceaccount.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement

#300 bump images
  charts/kubescape-operator/Chart.yaml
  charts/kubescape-operator/README.md
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement

#284 add rbac for application profile CRDs
  charts/kubescape-operator/templates/_helpers.tpl
  charts/kubescape-operator/templates/node-agent/clusterrole.yaml
  charts/kubescape-operator/templates/node-agent/configmap.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement

#283 Remove armo server URL from values.yaml
  charts/kubescape-operator/README.md
  charts/kubescape-operator/templates/kubescape/networkpolicy.yaml
  charts/kubescape-operator/values.yaml
Labels: Refactoring

#302 add argoCD application yaml
  ArgoCDApplication.yaml
  charts/kubescape-operator/templates/configs/cloudapi-configmap.yaml
  charts/kubescape-operator/templates/gateway/deployment.yaml
  charts/kubescape-operator/templates/gateway/role.yaml
  charts/kubescape-operator/templates/gateway/rolebinding.yaml
  charts/kubescape-operator/templates/gateway/serviceaccount.yaml
  charts/kubescape-operator/templates/kollector/role.yaml
  charts/kubescape-operator/templates/kollector/rolebinding.yaml
  charts/kubescape-operator/templates/kollector/statefulset.yaml
  charts/kubescape-operator/templates/kubescape/deployment.yaml
  charts/kubescape-operator/templates/kubevuln/deployment.yaml
  charts/kubescape-operator/templates/kubevuln/role.yaml
  charts/kubescape-operator/templates/kubevuln/rolebinding.yaml
  charts/kubescape-operator/templates/operator/deployment.yaml
  charts/kubescape-operator/templates/otel-collector/deployment.yaml
  charts/kubescape-operator/templates/otel-collector/role.yaml
  charts/kubescape-operator/templates/otel-collector/rolebinding.yaml
  charts/kubescape-operator/templates/otel-collector/serviceaccount.yaml
  charts/kubescape-operator/templates/servicediscovery/job.yaml
  charts/kubescape-operator/templates/servicediscovery/role.yaml
  charts/kubescape-operator/templates/servicediscovery/rolebinding.yaml
  charts/kubescape-operator/templates/servicediscovery/serviceaccount.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement

#304 added label to configmaps
  charts/kubescape-operator/templates/configs/cloudapi-configmap.yaml
  charts/kubescape-operator/templates/kubescape/configmap.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
Labels: enhancement

#303 feat: add the automatic upgrading capability
  charts/kubescape-operator/README.md
  charts/kubescape-operator/templates/autoupdater/cronjob.yaml
  charts/kubescape-operator/templates/autoupdater/rbac.yaml
  charts/kubescape-operator/templates/autoupdater/serviceaccount.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/tests/snapshot_test.yaml
  charts/kubescape-operator/values.yaml
Labels: enhancement, Tests

#299 add labels for servicemonitor
  charts/kubescape-operator/README.md
  charts/kubescape-operator/templates/kubescape/servicemonitor.yaml
Labels: enhancement

#301 Support Backend Access Key
  charts/kubescape-operator/templates/configs/cloud-secret.yaml
  charts/kubescape-operator/templates/configs/cloudapi-configmap.yaml
  charts/kubescape-operator/templates/gateway/deployment.yaml
  charts/kubescape-operator/templates/kollector/statefulset.yaml
  charts/kubescape-operator/templates/kubescape/configmap.yaml
  charts/kubescape-operator/templates/kubescape/deployment.yaml
  charts/kubescape-operator/templates/kubevuln/deployment.yaml
  charts/kubescape-operator/templates/operator/deployment.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement

#306 Removing privileged flag on the node-agent Pod
  charts/kubescape-operator/templates/node-agent/daemonset.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: Refactoring

#311 Add docker.io image registry identifier where missing
  charts/kubescape-operator/README.md
  charts/kubescape-operator/templates/storage/deployment.yaml
  charts/kubescape-operator/templates/storage/tests/test-connection.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement, Refactoring

#309 Adding Vex support in the helm-chart
  charts/kubescape-operator/templates/configs/cloudapi-configmap.yaml
  charts/kubescape-operator/templates/kubevuln/clusterrole.yaml
  charts/kubescape-operator/templates/operator/clusterrole.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement

#313 Adding resources to discovery job
  charts/kubescape-operator/templates/servicediscovery/job.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement

#316 Removing BPF/PERFMON capabilities (not supported in every kernel)
  charts/kubescape-operator/templates/node-agent/daemonset.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
Labels: Refactoring
