Repository kubescape/helm-charts, pull requests merged in 2023-11, with the labels that each got.

#324 Add account to storage & node-agent
  .gitignore
  charts/kubescape-operator/assets/host-scanner-definition.yaml
  charts/kubescape-operator/templates/gateway/deployment.yaml
  charts/kubescape-operator/templates/kollector/statefulset.yaml
  charts/kubescape-operator/templates/kubescape/deployment.yaml
  charts/kubescape-operator/templates/kubevuln/deployment.yaml
  charts/kubescape-operator/templates/node-agent/daemonset.yaml
  charts/kubescape-operator/templates/storage/deployment.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement

#323 feat: support the Continuous Scanning capability
  charts/kubescape-operator/README.md
  charts/kubescape-operator/templates/NOTES.txt
  charts/kubescape-operator/templates/configs/matchingRules-configmap.yaml
  charts/kubescape-operator/templates/operator/deployment.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement, release

#319 feat(serviceMonitor): Added option to customize interval and scrapeTi…
  charts/kubescape-operator/templates/kubescape/servicemonitor.yaml
  charts/kubescape-operator/values.yaml
Labels: enhancement

#317 Aks user assigned cluster support
  charts/kubescape-operator/README.md
  charts/kubescape-operator/templates/kubescape/deployment.yaml
Labels: enhancement

#321 Get busybox image from values file
  charts/kubescape-operator/templates/storage/deployment.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement

#325 Bump KS image tag
  charts/kubescape-operator/templates/_helpers.tpl
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement, Refactoring

#326 Network policies
  charts/kubescape-operator/README.md
  charts/kubescape-operator/templates/node-agent/clusterrole.yaml
  charts/kubescape-operator/templates/node-agent/configmap.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement, release

#328 Fixed limits
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: Bug fix

#330 Update NOTES.txt
  charts/kubescape-operator/templates/NOTES.txt
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement

#333 Update installation steps
  charts/kubescape-operator/README.md
Labels: documentation

#335 Fix restart
  charts/kubescape-operator/README.md
  charts/kubescape-operator/templates/_helpers.tpl
  charts/kubescape-operator/templates/gateway/deployment.yaml
  charts/kubescape-operator/templates/grype-offline-db/deployment.yaml
  charts/kubescape-operator/templates/kollector/statefulset.yaml
  charts/kubescape-operator/templates/kubescape/deployment.yaml
  charts/kubescape-operator/templates/kubescape/servicemonitor.yaml
  charts/kubescape-operator/templates/kubevuln/deployment.yaml
  charts/kubescape-operator/templates/node-agent/daemonset.yaml
  charts/kubescape-operator/templates/operator/deployment.yaml
  charts/kubescape-operator/templates/otel-collector/deployment.yaml
  charts/kubescape-operator/templates/servicediscovery/job.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: Refactoring

#336 release
  charts/kubescape-operator/Chart.yaml
  charts/kubescape-operator/README.md
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
Labels: enhancement, release

#337 Support for service discovery v2
  charts/kubescape-operator/templates/servicediscovery/job.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement

#339 removing storage initContainer no longer needed
  charts/kubescape-operator/templates/storage/deployment.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: Refactoring

#341 Release 1.16.4
  charts/kubescape-operator/Chart.yaml
  charts/kubescape-operator/README.md
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement, release
