Repository kubescape/helm-charts, pull requests merged in 2023-12, with the labels that each got.

#342 Delete duplicate parameters
  charts/kubescape-operator/values.yaml
Labels: Refactoring

#344 Support pre-created cloud secret
  charts/kubescape-operator/README.md
  charts/kubescape-operator/assets/host-scanner-definition.yaml
  charts/kubescape-operator/templates/_helpers.tpl
  charts/kubescape-operator/templates/configs/cloud-secret.yaml
  charts/kubescape-operator/templates/configs/components-configmap.yaml
  charts/kubescape-operator/templates/gateway/deployment.yaml
  charts/kubescape-operator/templates/kollector/statefulset.yaml
  charts/kubescape-operator/templates/kubescape/deployment.yaml
  charts/kubescape-operator/templates/kubevuln/deployment.yaml
  charts/kubescape-operator/templates/node-agent/daemonset.yaml
  charts/kubescape-operator/templates/operator/deployment.yaml
  charts/kubescape-operator/templates/storage/deployment.yaml
  charts/kubescape-operator/tests/README.md
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement

#345 Adding attributes/ksCloud processor
  charts/kubescape-operator/assets/otel-collector-config.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
Labels: enhancement

#334 add synchronizer client
  charts/kubescape-operator/templates/_helpers.tpl
  charts/kubescape-operator/templates/synchronizer/clusterrole.yaml
  charts/kubescape-operator/templates/synchronizer/clusterrolebinding.yaml
  charts/kubescape-operator/templates/synchronizer/configmap.yaml
  charts/kubescape-operator/templates/synchronizer/deployment.yaml
  charts/kubescape-operator/templates/synchronizer/networkpolicy.yaml
  charts/kubescape-operator/templates/synchronizer/serviceaccount.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/tests/snapshot_test.yaml
  charts/kubescape-operator/values.yaml
Labels: enhancement

#346 Bump version
  charts/kubescape-operator/Chart.yaml
  charts/kubescape-operator/README.md
  charts/kubescape-operator/templates/_helpers.tpl
  charts/kubescape-operator/templates/otel-collector/deployment.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement, Configuration changes

#347 Network policy
  charts/kubescape-operator/Chart.yaml
  charts/kubescape-operator/README.md
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement

#350 add np tests
  .github/workflows/02-e2e-test.yaml
Labels: Tests

#351 update objects to synchronize
  charts/kubescape-operator/templates/synchronizer/clusterrole.yaml
  charts/kubescape-operator/templates/synchronizer/configmap.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
Labels: enhancement

#349 wip: Ignore account id if secret exists
  charts/kubescape-operator/templates/_helpers.tpl
  charts/kubescape-operator/templates/kubescape/clusterrole.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
Labels: bug_fix

#356 update img
  charts/kubescape-operator/Chart.yaml
  charts/kubescape-operator/README.md
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement

#357 Adding an option to set the runtime path to node agent
  charts/kubescape-operator/README.md
  charts/kubescape-operator/templates/node-agent/daemonset.yaml
  charts/kubescape-operator/values.yaml
Labels: enhancement

#358 bump images
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement

#359 Global vars
  charts/kubescape-operator/README.md
  charts/kubescape-operator/assets/host-scanner-definition.yaml
  charts/kubescape-operator/assets/kubescape-cronjob-full.yaml
  charts/kubescape-operator/assets/kubevuln-cronjob-full.yaml
  charts/kubescape-operator/assets/registry-scan-cronjob-full.yaml
  charts/kubescape-operator/templates/gateway/deployment.yaml
  charts/kubescape-operator/templates/grype-offline-db/deployment.yaml
  charts/kubescape-operator/templates/kollector/statefulset.yaml
  charts/kubescape-operator/templates/kubescape-scheduler/cronjob.yaml
  charts/kubescape-operator/templates/kubescape/deployment.yaml
  charts/kubescape-operator/templates/kubevuln-scheduler/cronjob.yaml
  charts/kubescape-operator/templates/kubevuln/deployment.yaml
  charts/kubescape-operator/templates/node-agent/daemonset.yaml
  charts/kubescape-operator/templates/operator/deployment.yaml
  charts/kubescape-operator/templates/otel-collector/deployment.yaml
  charts/kubescape-operator/templates/servicediscovery/job.yaml
  charts/kubescape-operator/templates/storage/deployment.yaml
  charts/kubescape-operator/templates/synchronizer/deployment.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement

#360 bump node-agent and synchronizer, prepare for release
  charts/kubescape-operator/Chart.yaml
  charts/kubescape-operator/README.md
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement

#363 bump kubevuln
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement

#365 Hotfix naming convention
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement
