Repository kubescape/helm-charts, pull requests merged in 2024-02, with the labels that each got.

#387 Fix accessKey value
  charts/kubescape-operator/values.yaml
Labels: Bug fix, Review effort [1-5]: 1

#392 fix rbac permission for storage class
  charts/kubescape-operator/Chart.yaml
  charts/kubescape-operator/README.md
  charts/kubescape-operator/templates/kubescape/clusterrole.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
Labels: bug_fix, Review effort [1-5]: 1

#394 Synchronizer updates
  .github/workflows/02-e2e-test.yaml
  charts/kubescape-operator/templates/synchronizer/clusterrole.yaml
  charts/kubescape-operator/templates/synchronizer/configmap.yaml
  charts/kubescape-operator/templates/synchronizer/deployment.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement, Tests, Review effort [1-5]: 2

#391 fix: missing imagePullSecrets in storage deployment
  charts/kubescape-operator/templates/storage/deployment.yaml
Labels: bug_fix, Review effort [1-5]: 1

#398 Update ArgoCDApplication.yaml
  ArgoCDApplication.yaml
Labels: enhancement, Review effort [1-5]: 1

#399 add warning on upgrading releases with manual changes
  charts/kubescape-operator/README.md
Labels: documentation, Review effort [1-5]: 1

#400 Set default cluster name
  .github/workflows/kubescape.yaml
  charts/kubescape-operator/values.yaml
Labels: enhancement, Review effort [1-5]: 1
