Repository kubescape/helm-charts, pull requests merged in 2024-03, with the labels that each got.

#404 Reference to the official docs
  README.md
  charts/kubescape-operator/README.md
Labels: documentation, enhancement, Review effort [1-5]: 1

#402 add skip tls verify in registry creds secret
  charts/kubescape-operator/README.md
  charts/kubescape-operator/templates/configs/private-registries-creds-secret.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/tests/snapshot_test.yaml
  charts/kubescape-operator/values.yaml
Labels: enhancement, Possible security concern, Review effort [1-5]: 2

#401 Update ArgoCDApplication.yaml
  ArgoCDApplication.yaml
Labels: enhancement, Review effort [1-5]: 1

#405 prepare for next release
  charts/kubescape-operator/templates/operator/clusterrole.yaml
  charts/kubescape-operator/templates/operator/deployment.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement, Review effort [1-5]: 2

#407 bump chart version
  charts/kubescape-operator/Chart.yaml
  charts/kubescape-operator/README.md
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
Labels: enhancement

#408 updated synchronizer config, added tier label, bump nodeAgent and synchronizer
  charts/kubescape-operator/assets/host-scanner-definition.yaml
  charts/kubescape-operator/assets/kubescape-cronjob-full.yaml
  charts/kubescape-operator/assets/kubevuln-cronjob-full.yaml
  charts/kubescape-operator/assets/registry-scan-cronjob-full.yaml
  charts/kubescape-operator/templates/configs/cloudapi-configmap.yaml
  charts/kubescape-operator/templates/configs/components-configmap.yaml
  charts/kubescape-operator/templates/configs/matchingRules-configmap.yaml
  charts/kubescape-operator/templates/gateway/deployment.yaml
  charts/kubescape-operator/templates/grype-offline-db/deployment.yaml
  charts/kubescape-operator/templates/kollector/statefulset.yaml
  charts/kubescape-operator/templates/kubescape-scheduler/configmap.yaml
  charts/kubescape-operator/templates/kubescape-scheduler/cronjob.yaml
  charts/kubescape-operator/templates/kubescape/deployment.yaml
  charts/kubescape-operator/templates/kubescape/host-scanner-definition-configmap.yaml
  charts/kubescape-operator/templates/kubevuln-scheduler/configmap.yaml
  charts/kubescape-operator/templates/kubevuln-scheduler/cronjob.yaml
  charts/kubescape-operator/templates/kubevuln/deployment.yaml
  charts/kubescape-operator/templates/node-agent/configmap.yaml
  charts/kubescape-operator/templates/node-agent/daemonset.yaml
  charts/kubescape-operator/templates/operator/configmap.yaml
  charts/kubescape-operator/templates/operator/deployment.yaml
  charts/kubescape-operator/templates/operator/ks-recurring-cronjob-configmap.yaml
  charts/kubescape-operator/templates/operator/kv-recurring-cronjob-configmap.yaml
  charts/kubescape-operator/templates/operator/registry-scan-recurring-cronjob-configmap.yaml
  charts/kubescape-operator/templates/otel-collector/configmap.yaml
  charts/kubescape-operator/templates/otel-collector/deployment.yaml
  charts/kubescape-operator/templates/servicediscovery/job.yaml
  charts/kubescape-operator/templates/storage/deployment.yaml
  charts/kubescape-operator/templates/synchronizer/clusterrole.yaml
  charts/kubescape-operator/templates/synchronizer/configmap.yaml
  charts/kubescape-operator/templates/synchronizer/deployment.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement, Review effort [1-5]: 2

#413 added missing tier label
  charts/kubescape-operator/templates/gateway/deployment.yaml
  charts/kubescape-operator/templates/grype-offline-db/deployment.yaml
  charts/kubescape-operator/templates/kollector/statefulset.yaml
  charts/kubescape-operator/templates/kubescape/deployment.yaml
  charts/kubescape-operator/templates/kubevuln/deployment.yaml
  charts/kubescape-operator/templates/node-agent/daemonset.yaml
  charts/kubescape-operator/templates/operator/deployment.yaml
  charts/kubescape-operator/templates/otel-collector/deployment.yaml
  charts/kubescape-operator/templates/storage/deployment.yaml
  charts/kubescape-operator/templates/synchronizer/deployment.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
Labels: enhancement, Review effort [1-5]: 2

#412 Added chart repo addition command
  charts/kubescape-operator/README.md
Labels: documentation, Review effort [1-5]: 1

#414 prepare hotfix release for load creds
  MAINTAINERS.md
  charts/kubescape-operator/Chart.yaml
  charts/kubescape-operator/README.md
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: documentation, enhancement, Review effort [1-5]: 2
