Repository kubescape/helm-charts, pull requests merged in 2024-04, with the labels that each got.

#410 prepare smart remediation GA
  charts/kubescape-operator/Chart.yaml
  charts/kubescape-operator/README.md
  charts/kubescape-operator/templates/NOTES.txt
  charts/kubescape-operator/templates/kubescape-scheduler/cronjob.yaml
  charts/kubescape-operator/templates/kubevuln-scheduler/cronjob.yaml
  charts/kubescape-operator/templates/kubevuln/clusterrole.yaml
  charts/kubescape-operator/templates/node-agent/clusterrole.yaml
  charts/kubescape-operator/templates/operator/clusterrole.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement, Review effort [1-5]: 2

#415 prepare hotfix release
  .github/workflows/02-e2e-test.yaml
  charts/kubescape-operator/Chart.yaml
  charts/kubescape-operator/README.md
  charts/kubescape-operator/assets/kubescape-cronjob-full.yaml
  charts/kubescape-operator/assets/kubevuln-cronjob-full.yaml
  charts/kubescape-operator/assets/registry-scan-cronjob-full.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement, Review effort [1-5]: 2

#417 fix prometheus metrics
  charts/kubescape-operator/templates/node-agent/configmap.yaml
  charts/kubescape-operator/templates/node-agent/service.yaml
  charts/kubescape-operator/templates/node-agent/servicemonitor.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement, Configuration changes, Review effort [1-5]: 2

#418 Feature/new rules
  charts/kubescape-operator/crds/runtime-rule-binding.crd.yaml
  charts/kubescape-operator/templates/node-agent/default-rule-binding.yaml
Labels: enhancement, Review effort [1-5]: 2

#419 fix prometheus config
  charts/kubescape-operator/templates/kubescape/deployment.yaml
  charts/kubescape-operator/templates/node-agent/configmap.yaml
  charts/kubescape-operator/templates/node-agent/daemonset.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#416 Feat/rule detection
  .github/workflows/02-e2e-test.yaml
  .github/workflows/03-helm-release.yaml
  charts/kubescape-operator/README.md
  charts/kubescape-operator/clamav/clamd.conf
  charts/kubescape-operator/clamav/freshclam.conf
  charts/kubescape-operator/crds/runtime-rule-binding.crd.yaml
  charts/kubescape-operator/templates/_helpers.tpl
  charts/kubescape-operator/templates/kubescape/clusterrole.yaml
  charts/kubescape-operator/templates/kubescape/deployment.yaml
  charts/kubescape-operator/templates/kubevuln/clusterrole.yaml
  charts/kubescape-operator/templates/node-agent/clusterrole.yaml
  charts/kubescape-operator/templates/node-agent/configmap.yaml
  charts/kubescape-operator/templates/node-agent/daemonset.yaml
  charts/kubescape-operator/templates/node-agent/default-rule-binding.yaml
  charts/kubescape-operator/templates/node-agent/service.yaml
  charts/kubescape-operator/templates/node-agent/servicemonitor.yaml
  charts/kubescape-operator/templates/operator/clusterrole.yaml
  charts/kubescape-operator/templates/synchronizer/configmap.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#420 Update 03-helm-release.yaml
  .github/workflows/03-helm-release.yaml
Labels: enhancement, Review effort [1-5]: 1

#422 restore missing rbac for storage CRDs
  charts/kubescape-operator/Chart.yaml
  charts/kubescape-operator/README.md
  charts/kubescape-operator/templates/kubescape/clusterrole.yaml
  charts/kubescape-operator/templates/kubevuln/clusterrole.yaml
  charts/kubescape-operator/templates/operator/clusterrole.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
Labels: enhancement, Review effort [1-5]: 2

#424 Fixed SBOM encoding in storage
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement, Review effort [1-5]: 1

#425 add rbac and config for NetworkNeighborhood objects
  charts/kubescape-operator/templates/node-agent/clusterrole.yaml
  charts/kubescape-operator/templates/synchronizer/clusterrole.yaml
  charts/kubescape-operator/templates/synchronizer/configmap.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
Labels: enhancement, Review effort [1-5]: 2

#423 Node agent additional exporters config
  charts/kubescape-operator/Chart.yaml
  charts/kubescape-operator/templates/node-agent/configmap.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement, Review effort [1-5]: 2

#428 release workflow without tests
  .github/workflows/04-helm-release-no-tests.yaml
Labels: enhancement, Review effort [1-5]: 2

#430 Add permissions for storage classes and RBAC resources***
  charts/kubescape-operator/templates/synchronizer/clusterrole.yaml
  charts/kubescape-operator/templates/synchronizer/configmap.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
Labels: enhancement, Review effort [1-5]: 2

#431 bump kubevuln version
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement, Review effort [1-5]: 1
