Repository kubescape/helm-charts, pull requests merged in 2024-01, with the labels that each got.

#366 Version 1.17
  charts/kubescape-operator/Chart.yaml
  charts/kubescape-operator/README.md
  charts/kubescape-operator/templates/storage/deployment.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement

#367 bump version to 135
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement

#370 disable applicationprofile, networkpolicies - bump storage, synchronizer
  charts/kubescape-operator/Chart.yaml
  charts/kubescape-operator/README.md
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement

#288 Moreunittests
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/tests/snapshot_test.yaml
Labels: Tests

#371 Fail on missing access key
  charts/kubescape-operator/templates/_helpers.tpl
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/tests/snapshot_test.yaml
Labels: enhancement

#368 add cleanup interval and missing rbac for storage
  charts/kubescape-operator/templates/storage/clusterrole.yaml
  charts/kubescape-operator/templates/storage/deployment.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement

#373 fix cron templates
  charts/kubescape-operator/templates/kubescape-scheduler/cronjob.yaml
  charts/kubescape-operator/templates/kubevuln-scheduler/cronjob.yaml
  charts/kubescape-operator/templates/operator/ks-recurring-cronjob-configmap.yaml
  charts/kubescape-operator/templates/operator/kv-recurring-cronjob-configmap.yaml
  charts/kubescape-operator/templates/operator/registry-scan-recurring-cronjob-configmap.yaml
  charts/kubescape-operator/tests/snapshot_test.yaml
Labels: Bug fix

#374 prepare next release
  charts/kubescape-operator/Chart.yaml
  charts/kubescape-operator/README.md
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement

#375 Bump operator version
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement

#376 bump sync
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement

#343 Adding Prometheus Exporter to Helm Charts
  charts/kubescape-operator/templates/_helpers.tpl
  charts/kubescape-operator/templates/prometheus-exporter/clusterrole.yaml
  charts/kubescape-operator/templates/prometheus-exporter/clusterrolebinding.yaml
  charts/kubescape-operator/templates/prometheus-exporter/deployment.yaml
  charts/kubescape-operator/templates/prometheus-exporter/networkpolicy.yaml
  charts/kubescape-operator/templates/prometheus-exporter/service.yaml
  charts/kubescape-operator/templates/prometheus-exporter/serviceaccount.yaml
  charts/kubescape-operator/templates/prometheus-exporter/servicemonitor.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/tests/snapshot_test.yaml
  charts/kubescape-operator/values.yaml
Labels: enhancement

#377 revert merge mess
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/tests/snapshot_test.yaml
Labels: enhancement

#378 Prepare release 1.17.3
  .github/workflows/kubescape.yaml
  charts/kubescape-operator/Chart.yaml
  charts/kubescape-operator/README.md
  charts/kubescape-operator/templates/configs/cloudapi-configmap.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement

#379 Syft vs spdx
  charts/kubescape-operator/Chart.yaml
  charts/kubescape-operator/README.md
  charts/kubescape-operator/templates/gateway/deployment.yaml
  charts/kubescape-operator/templates/kollector/statefulset.yaml
  charts/kubescape-operator/templates/kubescape/deployment.yaml
  charts/kubescape-operator/templates/kubevuln/clusterrole.yaml
  charts/kubescape-operator/templates/node-agent/clusterrole.yaml
  charts/kubescape-operator/templates/operator/clusterrole.yaml
  charts/kubescape-operator/templates/operator/deployment.yaml
  charts/kubescape-operator/templates/otel-collector/deployment.yaml
  charts/kubescape-operator/templates/prometheus-exporter/deployment.yaml
  charts/kubescape-operator/templates/storage/deployment.yaml
  charts/kubescape-operator/templates/storage/pvc.yaml
  charts/kubescape-operator/templates/synchronizer/deployment.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement

#382 Add secret for private registries credentials
  charts/kubescape-operator/README.md
  charts/kubescape-operator/templates/configs/private-registries-creds-secret.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/tests/snapshot_test.yaml
  charts/kubescape-operator/values.yaml
Labels: enhancement, Possible security concern, Review effort [1-5]: 2

#381 bump images
  charts/kubescape-operator/templates/node-agent/daemonset.yaml
  charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
  charts/kubescape-operator/values.yaml
Labels: enhancement, Review effort [1-5]: 1
